spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://freelec-springboot2-webservice.cujr0knvcvjp.ap-northeast-2.rds.amazonaws.com:3306/freelec_springboot2_webservice?characterEncoding=UTF-8&serverTimezone=UTC
    username: liljay
    password: dudqk9696

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: DEBUG